experiment_id: "2025-11-18_missing_aware_aux_only_C10"
parent_id: "2025-11-16_missing_aware_baseline_a0"
date: "2025-11-18"
owner: "codex_agent"
dataset: "MIMIC-III in-hospital mortality"
task: "in-hospital-mortality"
change: "C10: SMART as pure regularizer — no pretraining, aux loss 0.01 with 0.1-0.3 masking, mask bias off"
belief:
  expected_final_gain: "small_positive"
  expected_stability_gain: "neutral"
  expected_convergence_speed_gain: "neutral"
config:
  command: "python train.py --epochs 100 --batch_size 256 --lr 1e-3 --weight_decay 0 --lambda_decov 1e-4 --amp --append_masks --papers_metrics_mode --missing_aware_extension --missing_aware_pretrain_epochs 0 --missing_aware_freeze_epochs 0 --missing_aware_mask_ratio_min 0.1 --missing_aware_mask_ratio_max 0.3 --missing_aware_disable_mask_bias --missing_aware_pretrain_lr 2e-4 --missing_aware_aux_weight 0.01 --keep_prob 0.5 --lr_scheduler none --early_stop_patience 10 --early_stop_min_delta 0.001 --cache_dir data/normalized_data_cache_train --instrument_signals --instrumentation_tag 2025-11-18_missing_aware_aux_only_C10"
  args:
    epochs: 100
    batch_size: 256
    lr: 0.001
    lr_scheduler: "none"
    weight_decay: 0.0
    lambda_decov: 0.0001
    amp: true
    device: "cuda"
    save_dir: "trained_models"
    results_dir: "results"
    cache_dir: "data/normalized_data_cache_train"
    timestep: 0.8
    append_masks: true
    diag: false
    compile: false
    papers_metrics_mode: true
    num_workers: -1
    model_variant: "concare_full"
    missing_aware_extension: true
    missing_aware_pretrain_epochs: 0
    missing_aware_pretrain_lr: 0.0002
    missing_aware_mask_ratio_min: 0.1
    missing_aware_mask_ratio_max: 0.3
    missing_aware_ema_decay: 0.99
    missing_aware_freeze_epochs: 0
    missing_aware_aux_weight: 0.01
    keep_prob: 0.5
    missing_aware_disable_mask_bias: true
    missing_aware_disable_temporal_attention: false
    cv_folds: 0
    cv_repeats: 1
    cv_pool_splits: "train,val"
    cv_val_ratio: 0.1
    cv_seed: 42
    early_stop_patience: 10
    early_stop_min_delta: 0.001
    parity_mode: false
    parity_train_dir: null
    parity_train_listfile: null
    parity_val_dir: null
    parity_val_listfile: null
    parity_test_dir: null
    parity_test_listfile: null
metrics:
  mimic_iii:
    val:
      best_epoch: 21
      auroc: 0.8427
      auprc: 0.5265
      f1: 0.5216
      precision: 0.4919
      recall: 0.555
      threshold: 0.41
    test_threshold_free:
      auroc: 0.8431
      auprc: 0.4614
      loss: 0.3075
    test_authors:
      acc: 0.873918
      auroc: 0.843112
      auprc: 0.460205
      minpse: 0.465241
      f1: 0.47013
      threshold: 0.41
    test_fixed_thr:
      threshold: 0.66
      acc: 0.8881
      f1: 0.4326
      minpse: 0.5541
    source: "Regenerated_Project_Code/results/train_val_test_log_2025-11-19_04-16-25.txt"
instrumentation:
  signal_check:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-18_missing_aware_aux_only_C10.json"
    status: "pending_run"
    summary: "Collect signal traces when SMART acts only as an auxiliary regularizer (no pretrain)."
  perturbations:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-18_missing_aware_aux_only_C10.json"
    missingness_curve: null
    truncation_curve: null
    notes: "Populate missingness/truncation sweeps once instrumentation completes."
effect_size:
  mimic_iii:
    vs_parent:
      info:
        run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-18_23-21-34.txt"
        SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-18_baseline_instrumented_a1.yaml"
      delta:
        val:
          best_epoch: -3
          auroc: 0.0029
          auprc: -0.0059
          f1: 0.0066
          precision: 0.0463
          recall: -0.0551
          threshold: -0.09
        test_threshold_free:
          auroc: -0.0045
          auprc: -0.004
          loss: -0.0424
        test_authors:
          acc: 0.024412
          auroc: -0.004538
          auprc: -0.003754
          minpse: -0.013369
          f1: -0.00565
          threshold: -0.09
        test_fixed_thr:
          threshold: 0.66
          acc: 0.008
          f1: -0.0402
          minpse: 0.0271
      pct:
        val:
          best_epoch: -0.125
          auroc: 0.003453
          auprc: -0.011082
          f1: 0.012816
          precision: 0.103905
          recall: -0.090313
          threshold: -0.18
        test_threshold_free:
          auroc: -0.005309
          auprc: -0.008595
          loss: -0.121177
        test_authors:
          acc: 0.028737
          auroc: -0.005354
          auprc: -0.008091
          minpse: -0.027933
          f1: -0.011875
          threshold: -0.18
        test_fixed_thr:
          threshold: 0.0
          acc: 0.00909
          f1: -0.085025
          minpse: 0.051423
    vs_siblings:
      sibling:
        info:
          run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-19_03-23-13.txt"
          SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-18_missing_aware_nopretrain_C7.yaml"
        delta:
          val:
            best_epoch: 0
            auroc: -0.0045
            auprc: -0.0066
            f1: -0.0026
            precision: 0.0075
            recall: -0.0161
            threshold: 0.07
          test_threshold_free:
            auroc: -0.0034
            auprc: -0.0066
            loss: 0.0035
          test_authors:
            acc: -0.008653
            auroc: -0.003358
            auprc: -0.006745
            minpse: -0.0072
            f1: 0.016107
            threshold: 0.07
          test_fixed_thr:
            threshold: 0.66
            acc: -0.0028
            f1: 0.0299
            minpse: -0.0126
        pct:
          val:
            best_epoch: 0.0
            auroc: -0.005312
            auprc: -0.01238
            f1: -0.00496
            precision: 0.015483
            recall: -0.028191
            threshold: 0.205882
          test_threshold_free:
            auroc: -0.004017
            auprc: -0.014103
            loss: 0.011513
          test_authors:
            acc: -0.009804
            auroc: -0.003967
            auprc: -0.014445
            minpse: -0.01524
            f1: 0.035476
            threshold: 0.205882
          test_fixed_thr:
            threshold: 0.66
            acc: -0.003143
            f1: 0.074249
            minpse: -0.022234

decision: "planned_run"
notes: >
  Goal: isolate the auxiliary latent loss contribution by turning SMART into a pure regularizer.
  Skip the reconstruction pretraining (pretrain_epochs=0, freeze=0) yet keep the mild mask ratios
  (0.1-0.3) with mask bias disabled, and add aux weight 0.01 during supervised training. Compare
  against the no-pretrain baseline (C7) to see whether aux alone can lift AUROC/AUPRC and strengthen
  robustness without pretraining side effects.
