experiment_id: "2025-11-16_missing_aware_pretrain20_C2"
parent_id: "2025-11-16_missing_aware_baseline_a0"
date: "2025-11-16"
owner: "codex_agent"
dataset: "MIMIC-III in-hospital mortality"
task: "in-hospital-mortality"
change: "Ablation: increase missing-aware pretrain epochs from 10 to 20 (same mask ratio/aux=0.01)"
belief:
  expected_final_gain: "negative"
  expected_stability_gain: "neutral"
  expected_convergence_speed_gain: "neutral"
config:
  command: "python train.py --epochs 100 --batch_size 256 --lr 1e-3 --amp --append_masks --papers_metrics_mode --missing_aware_extension --missing_aware_pretrain_epochs 20 --missing_aware_mask_ratio_min 0.2 --missing_aware_mask_ratio_max 0.5 --missing_aware_freeze_epochs 5 --missing_aware_aux_weight 0.01"
  args:
    epochs: 100
    batch_size: 256
    lr: 0.001
    lr_scheduler: "none"
    weight_decay: 0.0
    lambda_decov: 0.0001
    amp: true
    device: "cuda"
    save_dir: "trained_models"
    results_dir: "results"
    cache_dir: "data/normalized_data_cache_train"
    timestep: 0.8
    append_masks: true
    diag: false
    compile: false
    papers_metrics_mode: true
    num_workers: -1
    model_variant: "concare_full"
    missing_aware_extension: true
    missing_aware_pretrain_epochs: 20
    missing_aware_pretrain_lr: null
    missing_aware_mask_ratio_min: 0.2
    missing_aware_mask_ratio_max: 0.5
    missing_aware_ema_decay: 0.99
    missing_aware_freeze_epochs: 5
    missing_aware_aux_weight: 0.01
    keep_prob: 0.5
    missing_aware_disable_mask_bias: false
    missing_aware_disable_temporal_attention: false
    cv_folds: 0
    cv_repeats: 1
    cv_pool_splits: "train,val"
    cv_val_ratio: 0.1
    cv_seed: 42
    early_stop_patience: 0
    early_stop_min_delta: 0.0
    parity_mode: false
    parity_train_dir: null
    parity_train_listfile: null
    parity_val_dir: null
    parity_val_listfile: null
    parity_test_dir: null
    parity_test_listfile: null
metrics:
  mimic_iii:
    val:
      best_epoch: 28
      auroc: 0.8365
      auprc: 0.5233
      f1: 0.5026
      precision: 0.4576
      recall: 0.5573
      threshold: 0.64
    test_threshold_free:
      auroc: 0.848
      auprc: 0.4571
      loss: 0.3649
    test_authors:
      acc: 0.836836
      auroc: 0.848034
      auprc: 0.45603
      minpse: 0.475936
      f1: 0.478261
      threshold: 0.64
    test_fixed_thr:
      threshold: 0.66
      acc: 0.8687
      f1: 0.4886
      minpse: 0.5065
    source: "Regenerated_Project_Code/results/train_val_test_log_2025-11-16_18-01-39.txt"
instrumentation:
  signal_check:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-16_missing_aware_pretrain20_C2.json"
    status: "pending_run"
    summary: "Signal hooks wired up (--instrument_signals) but not executed for this log yet."
  perturbations:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-16_missing_aware_pretrain20_C2.json"
    missingness_curve: null
    truncation_curve: null
    notes: "Missingness/truncation sweeps will populate after instrumentation run."
effect_size:
  mimic_iii:
    vs_parent:
      info:
        run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-16_18-01-39.txt"
        SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-16_baseline_concare_ram.yaml"
      delta:
        val:
          best_epoch: 4
          auroc: -0.0033
          auprc: -0.0091
          f1: -0.0124
          precision: 0.012
          recall: -0.0528
          threshold: 0.14
        test_threshold_free:
          auroc: 0.0004
          auprc: -0.0083
          loss: 0.015
        test_authors:
          acc: -0.01267
          auroc: 0.000384
          auprc: -0.007929
          minpse: -0.002674
          f1: 0.002481
          threshold: 0.14
        test_fixed_thr:
          threshold: 0.66
          acc: -0.0114
          f1: 0.0158
          minpse: -0.0205
      pct:
        val:
          best_epoch: 0.166667
          auroc: -0.00393
          auprc: -0.017092
          f1: -0.024078
          precision: 0.02693
          recall: -0.086543
          threshold: 0.28
        test_threshold_free:
          auroc: 0.000472
          auprc: -0.017834
          loss: 0.042869
        test_authors:
          acc: -0.014915
          auroc: 0.000453
          auprc: -0.01709
          minpse: -0.005587
          f1: 0.005215
          threshold: 0.28
        test_fixed_thr:
          threshold: 0.66
          acc: -0.012953
          f1: 0.033418
          minpse: -0.038899
    vs_siblings:
      sibling:
        info:
          run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-16_16-57-08 best of both world.txt"
          SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-16_missing_aware_full_arch.yaml"
        delta:
          val:
            best_epoch: 15
            auroc: 0.0008
            auprc: 0.0034
            f1: 0.0011
            precision: 0.0225
            recall: -0.0344
            threshold: 0.06
          test_threshold_free:
            auroc: 0.0041
            auprc: -0.0051
            loss: -0.0013
          test_authors:
            acc: 0.009889
            auroc: 0.004183
            auprc: -0.005011
            minpse: 0.013369
            f1: 0.018802
            threshold: 0.06
          test_fixed_thr:
            threshold: 0.66
            acc: 0.0065
            f1: 0.0234
            minpse: -0.0233
        pct:
          val:
            best_epoch: 1.153846
            auroc: 0.000957
            auprc: 0.00654
            f1: 0.002193
            precision: 0.051712
            recall: -0.058138
            threshold: 0.103448
          test_threshold_free:
            auroc: 0.004858
            auprc: -0.011034
            loss: -0.00355
          test_authors:
            acc: 0.011958
            auroc: 0.004957
            auprc: -0.010869
            minpse: 0.028902
            f1: 0.040922
            threshold: 0.103448
          test_fixed_thr:
            threshold: 0.66
            acc: 0.007539
            f1: 0.050301
            minpse: -0.043979
decision: "reject"
notes: >
  Logged the first completed run for the 20-epoch missing-aware pretrain ablation (freeze=5, mask
  ratio 0.2-0.5). Validation AUROC/AUPRC (0.8365/0.5233) landed below the RAM baseline and the
  10-epoch SMART sibling, while threshold-free test AUROC plateaued at 0.8480 with lower AUPRC.
  Authors-style minPSE also trailed both references. Note: the raw log header reports
  `pretrain_epochs=10` and `aux_weight=0.0`, so double-check CLI wiring before rerunning this setup.
