experiment_id: "2025-11-18_missing_aware_maskbias_off_C4"
parent_id: "2025-11-16_missing_aware_baseline_a0"
date: "2025-11-18"
owner: "codex_agent"
dataset: "MIMIC-III in-hospital mortality"
task: "in-hospital-mortality"
change: "C4: keep mask-bias disabled but restore the wider mask sweep (0.2-0.5), missing-aware pretrain for 10 epochs and freeze encoder for 5 epochs. Figure out if missing_aware_disable_mask_bias cause improved result or reduced mark_ratio"
belief:
  expected_final_gain: "small_positive"
  expected_stability_gain: "neutral"
  expected_convergence_speed_gain: "neutral"
config:
  command: "python train.py --epochs 100 --batch_size 256 --lr 1e-3 --amp --append_masks --papers_metrics_mode --missing_aware_extension --missing_aware_pretrain_epochs 10 --missing_aware_mask_ratio_min 0.2 --missing_aware_mask_ratio_max 0.5 --missing_aware_freeze_epochs 5 --missing_aware_aux_weight 0.01 --missing_aware_disable_mask_bias --instrument_signals --instrumentation_tag 2025-11-18_missing_aware_maskbias_off_C4"
  args:
    epochs: 100
    batch_size: 256
    lr: 0.001
    lr_scheduler: "none"
    weight_decay: 0.0
    lambda_decov: 0.0001
    amp: true
    device: "cuda"
    save_dir: "trained_models"
    results_dir: "results"
    cache_dir: "data/normalized_data_cache_train"
    timestep: 0.8
    append_masks: true
    diag: false
    compile: false
    papers_metrics_mode: true
    num_workers: -1
    model_variant: "concare_full"
    missing_aware_extension: true
    missing_aware_pretrain_epochs: 10
    missing_aware_pretrain_lr: null
    missing_aware_mask_ratio_min: 0.2
    missing_aware_mask_ratio_max: 0.5
    missing_aware_ema_decay: 0.99
    missing_aware_freeze_epochs: 5
    missing_aware_aux_weight: 0.01
    keep_prob: 0.5
    missing_aware_disable_mask_bias: true
    missing_aware_disable_temporal_attention: false
    cv_folds: 0
    cv_repeats: 1
    cv_pool_splits: "train,val"
    cv_val_ratio: 0.1
    cv_seed: 42
    early_stop_patience: 0
    early_stop_min_delta: 0.0
    parity_mode: false
    parity_train_dir: null
    parity_train_listfile: null
    parity_val_dir: null
    parity_val_listfile: null
    parity_test_dir: null
    parity_test_listfile: null
metrics:
  mimic_iii:
    val:
      best_epoch: 41
      auroc: 0.8463
      auprc: 0.5311
      f1: 0.5097
      precision: 0.4798
      recall: 0.5436
      threshold: 0.42
    test_threshold_free:
      auroc: 0.8479
      auprc: 0.4731
      loss: 0.3069
    test_authors:
      acc: 0.875464
      auroc: 0.84792
      auprc: 0.472174
      minpse: 0.472
      f1: 0.475943
      threshold: 0.42
    test_fixed_thr:
      threshold: 0.66
      acc: 0.8844
      f1: 0.4333
      minpse: 0.5588
    source: "Regenerated_Project_Code/results/train_val_test_log_2025-11-19_00-08-49.txt"
instrumentation:
  signal_check:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-18_missing_aware_maskbias_off_C4.json"
    status: "pending_run"
    summary: "Capture gradient/activation stats for the wider-mask, bias-off configuration."
  perturbations:
    path: "Regenerated_Project_Code/instrumentation_data/2025-11-18_missing_aware_maskbias_off_C4.json"
    missingness_curve: null
    truncation_curve: null
    notes: "Missingness/truncation probes will populate once instrumentation completes."
effect_size:
  mimic_iii:
    vs_parent:
      info:
        run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-18_23-21-34.txt"
        SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-18_baseline_instrumented_a1.yaml"
      delta:
        val:
          best_epoch: 17
          auroc: 0.0065
          auprc: -0.0013
          f1: -0.0053
          precision: 0.0342
          recall: -0.0665
          threshold: -0.08
        test_threshold_free:
          auroc: 0.0003
          auprc: 0.0077
          loss: -0.043
        test_authors:
          acc: 0.025958
          auroc: 0.00027
          auprc: 0.008215
          minpse: -0.00661
          f1: 0.000163
          threshold: -0.08
        test_fixed_thr:
          threshold: 0.66
          acc: 0.0043
          f1: -0.0395
          minpse: 0.0318
      pct:
        val:
          best_epoch: 0.708333
          auroc: 0.00774
          auprc: -0.002442
          f1: -0.010291
          precision: 0.07675
          recall: -0.108999
          threshold: -0.16
        test_threshold_free:
          auroc: 0.000354
          auprc: 0.016545
          loss: -0.122892
        test_authors:
          acc: 0.030557
          auroc: 0.000319
          auprc: 0.017706
          minpse: -0.013811
          f1: 0.000343
          threshold: -0.16
        test_fixed_thr:
          threshold: 0.0
          acc: 0.004886
          f1: -0.083545
          minpse: 0.060342
    vs_siblings:
      sibling:
        info:
          run: "Regenerated_Project_Code/results/train_val_test_log_2025-11-18_21-24-40.txt"
          SEL: "Regenerated_Project_Code/experiment_logs/missing-aware/2025-11-16_missing_aware_maskbias_off_C3.yaml"
        delta:
          val:
            best_epoch: 6
            auroc: 0.0038
            auprc: 0.0005
            f1: -0.0093
            precision: 0.0189
            recall: -0.0504
            threshold: 0.14
          test_threshold_free:
            auroc: 0.0008
            auprc: 0.0096
            loss: -0.016
          test_authors:
            acc: -0.004326
            auroc: 0.000852
            auprc: 0.009718
            minpse: 0.0
            f1: 0.021525
            threshold: 0.14
          test_fixed_thr:
            threshold: 0.66
            acc: -0.0019
            f1: 0.0101
            minpse: -0.005
        pct:
          val:
            best_epoch: 0.171429
            auroc: 0.00451
            auprc: 0.000942
            f1: -0.017919
            precision: 0.041007
            recall: -0.084848
            threshold: 0.5
          test_threshold_free:
            auroc: 0.000944
            auprc: 0.020712
            loss: -0.049551
          test_authors:
            acc: -0.004917
            auroc: 0.001006
            auprc: 0.021014
            minpse: 0.0
            f1: 0.047368
            threshold: 0.5
          test_fixed_thr:
            threshold: 0.0
            acc: -0.002144
            f1: 0.023866
            minpse: -0.008868
decision: "planned_run"
notes: >
  Goal: test whether the wider SMART masking interval (0.2-0.5) recovers the AUROC gains from C1
  while keeping feature-level mask bias disabled as in C3. Keep the rest of the recipe the same
  (10 latent-pretrain epochs, freeze encoder for 5 epochs, aux weight 0.01) and log instrumentation
  to compare against C3/C1 traces once metrics land.
